
export const data = [
        {
            id: 1,
            img: 'S852I.png',
            type: 'Wiredheadphones',
            title: 'Apple BYZ S852I',
            price: 2927,
            rate: 4.7,
        },
        {
            id: 2,
            img: 'earpods1.png',
            type: 'Wiredheadphones',
            title: 'Apple EarPods',
            price: 2327,
            rate: 4.7,
        },
        {
            id: 3,
            img: 'earpods2.png',
            type: 'Wiredheadphones',
            title: 'Apple EarPods',
            price: 2327,
            rate: 4.5,
        },
        {
            id: 4,
            img: 'S852I.png',
            type: 'Wiredheadphones',
            title: 'Apple BYZ S852I',
            price: 2927,
            rate: 4.7,
        },
        {
            id: 5,
            img: 'earpods1.png',
            type: 'Wiredheadphones',
            title: 'Apple EarPods',
            price: 2327,
            rate: 4.7,
        },
        {
            id: 6,
            img: 'earpods2.png',
            type: 'Wiredheadphones',
            title: 'Apple EarPods',
            price: 2327,
            rate: 4.5,
        },
        {
            id: 7,
            img: 'airPods.png',
            type: 'Wirlessheadphones',
            title: 'Apple AirPods',
            price: 9527,
            rate: 4.7,
        },
        {
            id: 8,
            img: 'GERLAX.png',
            type: 'Wirlessheadphones',
            title: 'GERLAX GH-04',
            price: 6527,
            rate: 4.7,
        },
        {
            id: 9,
            img: 'BOROFONE.png',
            type: 'Wirlessheadphones',
            title: 'BOROFONE BO4',
            price: 7527,
            rate: 4.7,
        },
]
